/*



 */
package liblyapp.view;

import javax.swing.*;
import liblyapp.DAO.BDConnection;

/**
 *
 * @author Maysa
 */
public class Maine extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Maine() {
        initComponents();
        fecharTodasTelas();
        panel_inicial.setVisible(true);
    }
    private void fecharTodasTelas(){
        panel_inicial.setVisible(false);
        panel_login.setVisible(false);
        panel_cadastro.setVisible(false);
        panel_home.setVisible(false);
        panel_teachers.setVisible(false);
        panel_agendamento.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        call_frame = new javax.swing.JFrame();
        panel_inicial1 = new javax.swing.JPanel();
        body_inicial1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panel_inicial = new javax.swing.JPanel();
        body_inicial = new javax.swing.JPanel();
        btn_cad_ini = new javax.swing.JButton();
        btn_entrar_ini = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        body_login = new javax.swing.JPanel();
        txt_pw_log = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_aviso = new javax.swing.JLabel();
        txt_email_log = new javax.swing.JTextField();
        btn_entrar_log = new javax.swing.JButton();
        panel_top_login = new javax.swing.JPanel();
        btn_voltar = new javax.swing.JLabel();
        lbl_titulo_wel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel_cadastro = new javax.swing.JPanel();
        body_cadastro = new javax.swing.JPanel();
        txt_nome_cad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_cadastro_cad = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pw_cad = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_email_cad = new javax.swing.JTextField();
        panel_top_cadastro = new javax.swing.JPanel();
        btn_voltar_cad = new javax.swing.JLabel();
        lbl_titulo_wel2 = new javax.swing.JLabel();
        panel_home = new javax.swing.JPanel();
        panel_botoes_home = new javax.swing.JPanel();
        btn_perfil = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_procurar = new javax.swing.JButton();
        btn_materiais = new javax.swing.JButton();
        panel_top_home = new javax.swing.JPanel();
        lbl_titulo_wel1 = new javax.swing.JLabel();
        body_home = new javax.swing.JPanel();
        btn_professores = new javax.swing.JButton();
        btn_aulas = new javax.swing.JButton();
        panel_teachers = new javax.swing.JPanel();
        panel_top_prof = new javax.swing.JPanel();
        lbl_titulo_wel3 = new javax.swing.JLabel();
        body_prof = new javax.swing.JPanel();
        btn_att = new javax.swing.JButton();
        brn_agendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLAvalibleTeachers = new javax.swing.JList<>();
        panel_botoes_prof = new javax.swing.JPanel();
        btn_perfil3 = new javax.swing.JButton();
        btn_home3 = new javax.swing.JButton();
        btn_procurar1 = new javax.swing.JButton();
        btn_materiais1 = new javax.swing.JButton();
        panel_agendamento = new javax.swing.JPanel();
        panel_top_home1 = new javax.swing.JPanel();
        lbl_titulo_wel4 = new javax.swing.JLabel();
        body_agenda = new javax.swing.JPanel();
        btn_agendar = new javax.swing.JButton();
        jtf_professor1 = new javax.swing.JTextField();
        jtf_data = new javax.swing.JTextField();
        jtf_horario = new javax.swing.JTextField();
        cb_professor = new javax.swing.JComboBox<>();
        cb_data = new javax.swing.JComboBox<>();
        cb_horario = new javax.swing.JComboBox<>();
        panel_botoes_agendamento = new javax.swing.JPanel();
        btn_perfil1 = new javax.swing.JButton();
        btn_home1 = new javax.swing.JButton();
        btn_procurar2 = new javax.swing.JButton();
        btn_materiais2 = new javax.swing.JButton();

        call_frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        call_frame.setTitle("Libly");
        call_frame.setAlwaysOnTop(true);
        call_frame.setBackground(new java.awt.Color(0, 0, 0));
        call_frame.setBounds(new java.awt.Rectangle(300, 430, 0, 0));
        call_frame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        call_frame.setResizable(false);
        call_frame.setSize(new java.awt.Dimension(300, 430));
        call_frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_inicial1.setBackground(new java.awt.Color(88, 101, 242));
        panel_inicial1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        panel_inicial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body_inicial1.setBackground(new java.awt.Color(248, 248, 255));
        body_inicial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body_inicial1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, -1));

        panel_inicial1.add(body_inicial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 240, 360));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\images\\nuvem.png")); // NOI18N
        panel_inicial1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 270, 150));

        call_frame.getContentPane().add(panel_inicial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libly");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(300, 430, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setName("Jframe1"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(300, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_inicial.setBackground(new java.awt.Color(88, 101, 242));
        panel_inicial.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        panel_inicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body_inicial.setBackground(new java.awt.Color(248, 248, 255));
        body_inicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cad_ini.setBackground(new java.awt.Color(88, 101, 242));
        btn_cad_ini.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_cad_ini.setForeground(new java.awt.Color(255, 255, 255));
        btn_cad_ini.setText("Cadastrar-se");
        btn_cad_ini.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        btn_cad_ini.setBorderPainted(false);
        btn_cad_ini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cad_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cad_iniActionPerformed(evt);
            }
        });
        body_inicial.add(btn_cad_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 200, 30));

        btn_entrar_ini.setBackground(new java.awt.Color(88, 101, 242));
        btn_entrar_ini.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_entrar_ini.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar_ini.setText("Entrar");
        btn_entrar_ini.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        btn_entrar_ini.setBorderPainted(false);
        btn_entrar_ini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_entrar_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrar_iniActionPerformed(evt);
            }
        });
        body_inicial.add(btn_entrar_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 30));
        body_inicial.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, -1));

        jLabel10.setBackground(new java.awt.Color(248, 248, 255));
        jLabel10.setFont(new java.awt.Font("Segoe Script", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Libly");
        body_inicial.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 90));

        panel_inicial.add(body_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 240, 360));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\nuvem.png")); // NOI18N
        panel_inicial.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -50, -1, -1));

        getContentPane().add(panel_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        panel_login.setBackground(new java.awt.Color(88, 101, 242));
        panel_login.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body_login.setBackground(new java.awt.Color(248, 248, 255));
        body_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pw_log.setBackground(new java.awt.Color(255, 255, 255));
        body_login.add(txt_pw_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Senha:");
        body_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("E-mail:");
        body_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl_aviso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_aviso.setForeground(new java.awt.Color(255, 0, 51));
        body_login.add(lbl_aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 30));

        txt_email_log.setBackground(new java.awt.Color(255, 255, 255));
        body_login.add(txt_email_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 30));

        btn_entrar_log.setBackground(new java.awt.Color(88, 101, 242));
        btn_entrar_log.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_entrar_log.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar_log.setText("Entrar");
        btn_entrar_log.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        btn_entrar_log.setBorderPainted(false);
        btn_entrar_log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_entrar_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrar_logActionPerformed(evt);
            }
        });
        body_login.add(btn_entrar_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 30));

        panel_login.add(body_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 330));

        panel_top_login.setBackground(new java.awt.Color(255, 255, 255));
        panel_top_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_voltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\back.jpg")); // NOI18N
        btn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voltarMouseClicked(evt);
            }
        });
        panel_top_login.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 30));

        lbl_titulo_wel.setBackground(new java.awt.Color(255, 255, 255));
        lbl_titulo_wel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbl_titulo_wel.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo_wel.setText("Seja bem-vindo(a) de volta!");
        panel_top_login.add(lbl_titulo_wel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        panel_login.add(panel_top_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\images\\nuvem.png")); // NOI18N
        panel_login.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -50, 260, 150));

        getContentPane().add(panel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        panel_cadastro.setBackground(new java.awt.Color(88, 101, 242));
        panel_cadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        panel_cadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body_cadastro.setBackground(new java.awt.Color(248, 248, 255));
        body_cadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nome_cad.setBackground(new java.awt.Color(255, 255, 255));
        txt_nome_cad.setForeground(new java.awt.Color(0, 0, 0));
        body_cadastro.add(txt_nome_cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Senha:");
        body_cadastro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome");
        body_cadastro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btn_cadastro_cad.setBackground(new java.awt.Color(88, 101, 242));
        btn_cadastro_cad.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_cadastro_cad.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastro_cad.setText("Cadastrar-se");
        btn_cadastro_cad.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btn_cadastro_cad.setBorderPainted(false);
        btn_cadastro_cad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastro_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_cadActionPerformed(evt);
            }
        });
        body_cadastro.add(btn_cadastro_cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("E-mail:");
        body_cadastro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        pw_cad.setBackground(new java.awt.Color(255, 255, 255));
        pw_cad.setForeground(new java.awt.Color(0, 0, 0));
        body_cadastro.add(pw_cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 30));

        txt_tel.setBackground(new java.awt.Color(255, 255, 255));
        txt_tel.setForeground(new java.awt.Color(0, 0, 0));
        body_cadastro.add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telefone:");
        body_cadastro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txt_cpf.setBackground(new java.awt.Color(255, 255, 255));
        txt_cpf.setForeground(new java.awt.Color(0, 0, 0));
        body_cadastro.add(txt_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CPF:");
        body_cadastro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txt_email_cad.setBackground(new java.awt.Color(255, 255, 255));
        txt_email_cad.setForeground(new java.awt.Color(0, 0, 0));
        body_cadastro.add(txt_email_cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, 30));

        panel_cadastro.add(body_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 330));

        panel_top_cadastro.setBackground(new java.awt.Color(255, 255, 255));
        panel_top_cadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_voltar_cad.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\back.jpg")); // NOI18N
        btn_voltar_cad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar_cad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voltar_cadMouseClicked(evt);
            }
        });
        panel_top_cadastro.add(btn_voltar_cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 30));

        lbl_titulo_wel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbl_titulo_wel2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo_wel2.setText("Vamos começar!");
        panel_top_cadastro.add(lbl_titulo_wel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        panel_cadastro.add(panel_top_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        getContentPane().add(panel_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        panel_home.setBackground(new java.awt.Color(88, 101, 242));
        panel_home.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        panel_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_botoes_home.setBackground(new java.awt.Color(180, 165, 202));
        panel_botoes_home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_botoes_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_perfil.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\perfil.jpg")); // NOI18N
        panel_botoes_home.add(btn_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, 30));

        btn_home.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\home.jpg")); // NOI18N
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        panel_botoes_home.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        btn_procurar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\search.jpg")); // NOI18N
        btn_procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procurarActionPerformed(evt);
            }
        });
        panel_botoes_home.add(btn_procurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 30, 30));

        btn_materiais.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\materiais.jpg")); // NOI18N
        panel_botoes_home.add(btn_materiais, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 30, 30));

        panel_home.add(panel_botoes_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 50));

        panel_top_home.setBackground(new java.awt.Color(255, 255, 255));
        panel_top_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo_wel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbl_titulo_wel1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo_wel1.setText("Home");
        panel_top_home.add(lbl_titulo_wel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, -1));

        panel_home.add(panel_top_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        body_home.setBackground(new java.awt.Color(248, 248, 255));
        body_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_professores.setBackground(new java.awt.Color(88, 101, 242));
        btn_professores.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btn_professores.setForeground(new java.awt.Color(255, 255, 255));
        btn_professores.setText("Encontrar professores");
        btn_professores.setBorderPainted(false);
        btn_professores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_professoresActionPerformed(evt);
            }
        });
        body_home.add(btn_professores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 40));

        btn_aulas.setBackground(new java.awt.Color(88, 101, 242));
        btn_aulas.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btn_aulas.setForeground(new java.awt.Color(255, 255, 255));
        btn_aulas.setText("Aulas disponíveis");
        btn_aulas.setBorderPainted(false);
        body_home.add(btn_aulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 40));

        panel_home.add(body_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 280));

        getContentPane().add(panel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        panel_teachers.setBackground(new java.awt.Color(88, 101, 242));
        panel_teachers.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        panel_teachers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_top_prof.setBackground(new java.awt.Color(255, 255, 255));
        panel_top_prof.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo_wel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbl_titulo_wel3.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo_wel3.setText("Professores");
        panel_top_prof.add(lbl_titulo_wel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, -1));

        panel_teachers.add(panel_top_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        body_prof.setBackground(new java.awt.Color(248, 248, 255));
        body_prof.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_att.setBackground(new java.awt.Color(88, 101, 242));
        btn_att.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btn_att.setForeground(new java.awt.Color(255, 255, 255));
        btn_att.setText("Atualizar");
        btn_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attActionPerformed(evt);
            }
        });
        body_prof.add(btn_att, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        brn_agendar.setBackground(new java.awt.Color(88, 101, 242));
        brn_agendar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        brn_agendar.setForeground(new java.awt.Color(255, 255, 255));
        brn_agendar.setText("Agendar");
        brn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_agendarActionPerformed(evt);
            }
        });
        body_prof.add(brn_agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLAvalibleTeachers.setBackground(new java.awt.Color(255, 255, 255));
        jLAvalibleTeachers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLAvalibleTeachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAvalibleTeachersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLAvalibleTeachers);

        body_prof.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 280));

        panel_teachers.add(body_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 280));

        panel_botoes_prof.setBackground(new java.awt.Color(180, 165, 202));
        panel_botoes_prof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_botoes_prof.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_perfil3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\perfil.jpg")); // NOI18N
        panel_botoes_prof.add(btn_perfil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, 30));

        btn_home3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\home.jpg")); // NOI18N
        btn_home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home3ActionPerformed(evt);
            }
        });
        panel_botoes_prof.add(btn_home3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        btn_procurar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\search.jpg")); // NOI18N
        btn_procurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procurar1ActionPerformed(evt);
            }
        });
        panel_botoes_prof.add(btn_procurar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 30, 30));

        btn_materiais1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\materiais.jpg")); // NOI18N
        panel_botoes_prof.add(btn_materiais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 30, 30));

        panel_teachers.add(panel_botoes_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 50));

        getContentPane().add(panel_teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        panel_agendamento.setBackground(new java.awt.Color(88, 101, 242));
        panel_agendamento.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        panel_agendamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_top_home1.setBackground(new java.awt.Color(255, 255, 255));
        panel_top_home1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo_wel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbl_titulo_wel4.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo_wel4.setText("Agendamento");
        panel_top_home1.add(lbl_titulo_wel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, -1));

        panel_agendamento.add(panel_top_home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        body_agenda.setBackground(new java.awt.Color(248, 248, 255));
        body_agenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agendar.setBackground(new java.awt.Color(88, 101, 242));
        btn_agendar.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_agendar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agendar.setText("Agendar");
        btn_agendar.setBorderPainted(false);
        btn_agendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarActionPerformed(evt);
            }
        });
        body_agenda.add(btn_agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, 40));

        jtf_professor1.setBackground(new java.awt.Color(180, 165, 202));
        jtf_professor1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jtf_professor1.setForeground(new java.awt.Color(0, 0, 0));
        jtf_professor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_professor1.setText("Professor:");
        jtf_professor1.setMaximumSize(new java.awt.Dimension(70, 25));
        jtf_professor1.setMinimumSize(new java.awt.Dimension(70, 25));
        jtf_professor1.setPreferredSize(new java.awt.Dimension(70, 25));
        jtf_professor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_professor1ActionPerformed(evt);
            }
        });
        body_agenda.add(jtf_professor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 30));

        jtf_data.setBackground(new java.awt.Color(180, 165, 202));
        jtf_data.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jtf_data.setForeground(new java.awt.Color(0, 0, 0));
        jtf_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_data.setText("Data:");
        jtf_data.setMaximumSize(new java.awt.Dimension(70, 25));
        jtf_data.setMinimumSize(new java.awt.Dimension(70, 25));
        jtf_data.setPreferredSize(new java.awt.Dimension(70, 25));
        jtf_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_dataActionPerformed(evt);
            }
        });
        body_agenda.add(jtf_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        jtf_horario.setBackground(new java.awt.Color(180, 165, 202));
        jtf_horario.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jtf_horario.setForeground(new java.awt.Color(0, 0, 0));
        jtf_horario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_horario.setText("Horário:");
        jtf_horario.setMaximumSize(new java.awt.Dimension(70, 25));
        jtf_horario.setMinimumSize(new java.awt.Dimension(70, 25));
        jtf_horario.setPreferredSize(new java.awt.Dimension(70, 25));
        jtf_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_horarioActionPerformed(evt);
            }
        });
        body_agenda.add(jtf_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 30));

        cb_professor.setBackground(new java.awt.Color(255, 255, 255));
        cb_professor.setEditable(true);
        cb_professor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_professor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João", "Ricardo", "Maria", "Letícia", "Roberto", "Roque", "Ana Clara", "Diego" }));
        cb_professor.setMaximumSize(new java.awt.Dimension(70, 25));
        cb_professor.setMinimumSize(new java.awt.Dimension(70, 25));
        cb_professor.setPreferredSize(new java.awt.Dimension(70, 25));
        cb_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_professorActionPerformed(evt);
            }
        });
        body_agenda.add(cb_professor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 100, 30));

        cb_data.setBackground(new java.awt.Color(255, 255, 255));
        cb_data.setEditable(true);
        cb_data.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_data.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01-02-2022", "02-02-2022", "06-02-2022", "07-02-2022", "08-02-2022", "09-02-2022", "10-02-2022", "11-02-2022", "12-02-2022", "14-02-2022", "16-02-2022", "18-02-2022", "20-02-2022", "21-02-2022", "22-02-2022", "23-02-2022", "24-02-2022", "28-02-2022", " " }));
        cb_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dataActionPerformed(evt);
            }
        });
        body_agenda.add(cb_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, 30));

        cb_horario.setBackground(new java.awt.Color(255, 255, 255));
        cb_horario.setEditable(true);
        cb_horario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", " ", " ", " " }));
        body_agenda.add(cb_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, 30));

        panel_agendamento.add(body_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 280));

        panel_botoes_agendamento.setBackground(new java.awt.Color(180, 165, 202));
        panel_botoes_agendamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_botoes_agendamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_perfil1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\perfil.jpg")); // NOI18N
        panel_botoes_agendamento.add(btn_perfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, 30));

        btn_home1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\home.jpg")); // NOI18N
        btn_home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home1ActionPerformed(evt);
            }
        });
        panel_botoes_agendamento.add(btn_home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        btn_procurar2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\search.jpg")); // NOI18N
        btn_procurar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procurar2ActionPerformed(evt);
            }
        });
        panel_botoes_agendamento.add(btn_procurar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 30, 30));

        btn_materiais2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Desktop\\IFSP HTO\\problemas\\LiblyApp\\src\\main\\resources\\images\\materiais.jpg")); // NOI18N
        panel_botoes_agendamento.add(btn_materiais2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 30, 30));

        panel_agendamento.add(panel_botoes_agendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 50));

        getContentPane().add(panel_agendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voltarMouseClicked
        fecharTodasTelas();
        panel_inicial.setVisible(true);
        
    }//GEN-LAST:event_btn_voltarMouseClicked

    private void btn_voltar_cadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voltar_cadMouseClicked
        fecharTodasTelas();
        panel_inicial.setVisible(true);
    }//GEN-LAST:event_btn_voltar_cadMouseClicked

    private void btn_cadastro_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_cadActionPerformed
        BDConnection bd = new BDConnection();
        bd.conectarBanco();
        bd.bdCadastrarAluno(txt_nome_cad.getText(), txt_email_cad.getText(), pw_cad.getText(), txt_tel.getText(), txt_cpf.getText());
        fecharTodasTelas();
        panel_home.setVisible(true);
    }//GEN-LAST:event_btn_cadastro_cadActionPerformed

    private void btn_entrar_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrar_iniActionPerformed
        fecharTodasTelas();
        panel_login.setVisible(true);
    }//GEN-LAST:event_btn_entrar_iniActionPerformed

    private void btn_cad_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cad_iniActionPerformed
        fecharTodasTelas();
        panel_cadastro.setVisible(true);
    }//GEN-LAST:event_btn_cad_iniActionPerformed

    private void btn_entrar_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrar_logActionPerformed
      BDConnection bd = new BDConnection();
        bd.conectarBanco();
        String senha = bd.bdConsultarLoginAluno(txt_email_log.getText());

        if(senha == null){
            lbl_aviso.setText("Usuário não cadastrado!!!");
        }else{
            if(txt_pw_log.getText().equals(senha)){
                lbl_aviso.setText("Senha correta, aguarde...");
                fecharTodasTelas();
                panel_home.setVisible(true);
            }else{
                lbl_aviso.setText("Senha incorreta!");
            }
        }
    }//GEN-LAST:event_btn_entrar_logActionPerformed

    private void btn_professoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_professoresActionPerformed
        fecharTodasTelas();
        panel_teachers.setVisible(true);
    }//GEN-LAST:event_btn_professoresActionPerformed

    private void btn_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attActionPerformed
        jLAvalibleTeachers.setModel(new javax.swing.AbstractListModel<String>() {
            public String[] strings = {"João", "Ricardo", "Maria", "Letícia", "Roberto", "Roque", "Ana Clara", "Diego"};
            
            @Override
            public int getSize() {return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_btn_attActionPerformed

    private void btn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarActionPerformed
        JOptionPane.showMessageDialog(this, " AULA  AGENDADA COM SUCESSO!!! \n\n "
            +"\nProfessor: " +cb_professor.getSelectedItem()
            +"\nAgendado dia: " + cb_data.getSelectedItem()
            +" as " +cb_horario.getSelectedItem()
        );
    }//GEN-LAST:event_btn_agendarActionPerformed

    private void jtf_professor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_professor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_professor1ActionPerformed

    private void jtf_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dataActionPerformed

    private void jtf_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_horarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_horarioActionPerformed

    private void cb_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dataActionPerformed

    private void cb_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_professorActionPerformed

    }//GEN-LAST:event_cb_professorActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        fecharTodasTelas();
        panel_home.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procurarActionPerformed
        fecharTodasTelas();
        panel_teachers.setVisible(true);
    }//GEN-LAST:event_btn_procurarActionPerformed

    private void btn_home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home3ActionPerformed
        fecharTodasTelas();
        panel_home.setVisible(true);
    }//GEN-LAST:event_btn_home3ActionPerformed

    private void btn_procurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procurar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_procurar1ActionPerformed

    private void btn_home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home1ActionPerformed
        fecharTodasTelas();
        panel_home.setVisible(true);
    }//GEN-LAST:event_btn_home1ActionPerformed

    private void btn_procurar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procurar2ActionPerformed
        fecharTodasTelas();
        panel_teachers.setVisible(true);
    }//GEN-LAST:event_btn_procurar2ActionPerformed

    private void jLAvalibleTeachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAvalibleTeachersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLAvalibleTeachersMouseClicked

    private void brn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_agendarActionPerformed
       fecharTodasTelas();
       panel_agendamento.setVisible(true);
    }//GEN-LAST:event_brn_agendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body_agenda;
    private javax.swing.JPanel body_cadastro;
    private javax.swing.JPanel body_home;
    private javax.swing.JPanel body_inicial;
    private javax.swing.JPanel body_inicial1;
    private javax.swing.JPanel body_login;
    private javax.swing.JPanel body_prof;
    private javax.swing.JButton brn_agendar;
    private javax.swing.JButton btn_agendar;
    private javax.swing.JButton btn_att;
    private javax.swing.JButton btn_aulas;
    private javax.swing.JButton btn_cad_ini;
    private javax.swing.JButton btn_cadastro_cad;
    private javax.swing.JButton btn_entrar_ini;
    private javax.swing.JButton btn_entrar_log;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_home1;
    private javax.swing.JButton btn_home3;
    private javax.swing.JButton btn_materiais;
    private javax.swing.JButton btn_materiais1;
    private javax.swing.JButton btn_materiais2;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JButton btn_perfil1;
    private javax.swing.JButton btn_perfil3;
    private javax.swing.JButton btn_procurar;
    private javax.swing.JButton btn_procurar1;
    private javax.swing.JButton btn_procurar2;
    private javax.swing.JButton btn_professores;
    private javax.swing.JLabel btn_voltar;
    private javax.swing.JLabel btn_voltar_cad;
    private javax.swing.JFrame call_frame;
    private javax.swing.JComboBox<String> cb_data;
    private javax.swing.JComboBox<String> cb_horario;
    private javax.swing.JComboBox<String> cb_professor;
    private javax.swing.JList<String> jLAvalibleTeachers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf_data;
    private javax.swing.JTextField jtf_horario;
    private javax.swing.JTextField jtf_professor1;
    private javax.swing.JLabel lbl_aviso;
    private javax.swing.JLabel lbl_titulo_wel;
    private javax.swing.JLabel lbl_titulo_wel1;
    private javax.swing.JLabel lbl_titulo_wel2;
    private javax.swing.JLabel lbl_titulo_wel3;
    private javax.swing.JLabel lbl_titulo_wel4;
    private javax.swing.JPanel panel_agendamento;
    private javax.swing.JPanel panel_botoes_agendamento;
    private javax.swing.JPanel panel_botoes_home;
    private javax.swing.JPanel panel_botoes_prof;
    private javax.swing.JPanel panel_cadastro;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_inicial;
    private javax.swing.JPanel panel_inicial1;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_teachers;
    private javax.swing.JPanel panel_top_cadastro;
    private javax.swing.JPanel panel_top_home;
    private javax.swing.JPanel panel_top_home1;
    private javax.swing.JPanel panel_top_login;
    private javax.swing.JPanel panel_top_prof;
    private javax.swing.JTextField pw_cad;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email_cad;
    private javax.swing.JTextField txt_email_log;
    private javax.swing.JTextField txt_nome_cad;
    private javax.swing.JTextField txt_pw_log;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
