/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package liblyapp.view;

import javax.swing.*;
import liblyapp.DAO.BDConnection;

/**
 *
 * @author Ubuntu
 */
public class MainScreen extends javax.swing.JFrame {

    
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        jPLogin.setVisible(true);
        jPLoginCadastrar.setVisible(false);
        jPLoginEntrar.setVisible(false);
        jPHome.setVisible(false);
        jPTeachers.setVisible(false);
        jPSchedule.setVisible(false);
        jPConfigs.setVisible(false);
    }
        
    private void fecharTodasTelas(){
        jPLogin.setVisible(false);
        jPLoginCadastrar.setVisible(false);
        jPLoginEntrar.setVisible(false);
        jPHome.setVisible(false);
        jPTeachers.setVisible(false);
        jPSchedule.setVisible(false);
        jPConfigs.setVisible(false);
    }
    
    
    private void voltarJanelaLogin(){
        fecharTodasTelas();
        jPLogin.setVisible(true);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPLogin = new javax.swing.JPanel();
        panel_ini = new javax.swing.JPanel();
        jBCadastrar = new javax.swing.JButton();
        jBEntrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPLoginCadastrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jTFSenha = new javax.swing.JTextField();
        jBRegister = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLVoltar = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFTelefone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTFCPF = new javax.swing.JTextField();
        jPLoginEntrar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFLoginEmail = new javax.swing.JTextField();
        jTFLoginSenha = new javax.swing.JTextField();
        jBLogin = new javax.swing.JButton();
        jLVoltar2 = new javax.swing.JLabel();
        jLInformacoes = new javax.swing.JLabel();
        jPHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPTeachers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLAvalibleTeachers = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPSchedule = new javax.swing.JPanel();
        cb_professor = new javax.swing.JComboBox<>();
        cb_data = new javax.swing.JComboBox<>();
        cb_horario = new javax.swing.JComboBox<>();
        jtf_horario = new javax.swing.JTextField();
        jtf_professor1 = new javax.swing.JTextField();
        jtf_data = new javax.swing.JTextField();
        btn_agendar = new javax.swing.JButton();
        jPConfigs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBHome = new javax.swing.JButton();
        jBSearch = new javax.swing.JButton();
        jBSchedule = new javax.swing.JButton();
        jBConfiguration = new javax.swing.JButton();
        panel_body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 430));
        setMinimumSize(new java.awt.Dimension(300, 430));
        setPreferredSize(new java.awt.Dimension(300, 590));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPLogin.setBackground(new java.awt.Color(3, 152, 158));
        jPLogin.setMaximumSize(new java.awt.Dimension(300, 430));
        jPLogin.setMinimumSize(new java.awt.Dimension(300, 430));
        jPLogin.setPreferredSize(new java.awt.Dimension(300, 430));
        jPLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_ini.setBackground(new java.awt.Color(255, 255, 255));
        panel_ini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBCadastrar.setBackground(new java.awt.Color(124, 188, 196));
        jBCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBCadastrar.setText("CADASTRAR-SE");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });
        panel_ini.add(jBCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 220, 46));

        jBEntrar.setBackground(new java.awt.Color(124, 188, 196));
        jBEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBEntrar.setText("LOGIN");
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });
        panel_ini.add(jBEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 220, 46));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maysa\\Documents\\NetBeansProjects\\Libly_2\\src\\main\\image\\logo.png")); // NOI18N
        panel_ini.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 150));

        jPLogin.add(panel_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 260, 380));

        getContentPane().add(jPLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        jPLoginCadastrar.setBackground(new java.awt.Color(3, 152, 158));
        jPLoginCadastrar.setMaximumSize(null);
        jPLoginCadastrar.setPreferredSize(new java.awt.Dimension(300, 430));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vamos Começar!");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Senha:");

        jBRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBRegister.setText("Cadastrar-se");
        jBRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegisterActionPerformed(evt);
            }
        });

        jLVoltar.setText("voltar");
        jLVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLVoltarMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefone:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CPF:");

        javax.swing.GroupLayout jPLoginCadastrarLayout = new javax.swing.GroupLayout(jPLoginCadastrar);
        jPLoginCadastrar.setLayout(jPLoginCadastrarLayout);
        jPLoginCadastrarLayout.setHorizontalGroup(
            jPLoginCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoginCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(126, 126, 126))
            .addGroup(jPLoginCadastrarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPLoginCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jBRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jTFCPF)
                    .addComponent(jTFTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jTFSenha)
                    .addComponent(jTFEmail)
                    .addComponent(jTFNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPLoginCadastrarLayout.setVerticalGroup(
            jPLoginCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginCadastrarLayout.createSequentialGroup()
                .addGroup(jPLoginCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLoginCadastrarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPLoginCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoginCadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPLoginCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        jPLoginEntrar.setBackground(new java.awt.Color(3, 152, 158));
        jPLoginEntrar.setMaximumSize(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Seja bem-vindo(a) de volta");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("E-mail:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Senha:");

        jBLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBLogin.setText("Entrar");
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });

        jLVoltar2.setText("voltar");
        jLVoltar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLVoltar2MouseClicked(evt);
            }
        });

        jLInformacoes.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPLoginEntrarLayout = new javax.swing.GroupLayout(jPLoginEntrar);
        jPLoginEntrar.setLayout(jPLoginEntrarLayout);
        jPLoginEntrarLayout.setHorizontalGroup(
            jPLoginEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoginEntrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(81, 81, 81))
            .addGroup(jPLoginEntrarLayout.createSequentialGroup()
                .addGroup(jPLoginEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLoginEntrarLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPLoginEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFLoginSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(jTFLoginEmail)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)))
                    .addGroup(jPLoginEntrarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPLoginEntrarLayout.setVerticalGroup(
            jPLoginEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginEntrarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPLoginEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPLoginEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        jPHome.setBackground(new java.awt.Color(3, 152, 158));
        jPHome.setMaximumSize(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Libly");

        jButton1.setText("SEU PLANO ATUAL");

        jButton3.setText("ESCOLHER UM NOVO PLANO");
        jButton3.setToolTipText("");

        jButton4.setText("ENCONTRAR PROFESSORES DISPONÍVEIS");
        jButton4.setToolTipText("");

        javax.swing.GroupLayout jPHomeLayout = new javax.swing.GroupLayout(jPHome);
        jPHome.setLayout(jPHomeLayout);
        jPHomeLayout.setHorizontalGroup(
            jPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHomeLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHomeLayout.createSequentialGroup()
                .addGroup(jPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPHomeLayout.setVerticalGroup(
            jPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHomeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        getContentPane().add(jPHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        jPTeachers.setBackground(new java.awt.Color(3, 152, 158));
        jPTeachers.setMaximumSize(null);

        jLAvalibleTeachers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jLAvalibleTeachers);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Professores");

        jButton2.setText("Procurar professores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTeachersLayout = new javax.swing.GroupLayout(jPTeachers);
        jPTeachers.setLayout(jPTeachersLayout);
        jPTeachersLayout.setHorizontalGroup(
            jPTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTeachersLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTeachersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPTeachersLayout.setVerticalGroup(
            jPTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTeachersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        jPSchedule.setBackground(new java.awt.Color(3, 152, 158));
        jPSchedule.setMaximumSize(null);

        cb_professor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_professor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João", "Ricardo", "Maria", "Letícia", "Roberto", "Roque", "Ana Clara", "Diego" }));
        cb_professor.setMaximumSize(new java.awt.Dimension(70, 25));
        cb_professor.setMinimumSize(new java.awt.Dimension(70, 25));
        cb_professor.setPreferredSize(new java.awt.Dimension(70, 25));

        cb_data.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_data.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01-02-2022", "02-02-2022", "06-02-2022", "07-02-2022", "08-02-2022", "09-02-2022", "10-02-2022", "11-02-2022", "12-02-2022", "14-02-2022", "16-02-2022", "18-02-2022", "20-02-2022", "21-02-2022", "22-02-2022", "23-02-2022", "24-02-2022", "28-02-2022", " " }));
        cb_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dataActionPerformed(evt);
            }
        });

        cb_horario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", " ", " ", " " }));

        jtf_horario.setBackground(new java.awt.Color(168, 214, 209));
        jtf_horario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtf_horario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_horario.setText("Horário:");
        jtf_horario.setMaximumSize(new java.awt.Dimension(70, 25));
        jtf_horario.setMinimumSize(new java.awt.Dimension(70, 25));
        jtf_horario.setPreferredSize(new java.awt.Dimension(70, 25));
        jtf_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_horarioActionPerformed(evt);
            }
        });

        jtf_professor1.setBackground(new java.awt.Color(168, 214, 209));
        jtf_professor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtf_professor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_professor1.setText("Professor:");
        jtf_professor1.setMaximumSize(new java.awt.Dimension(70, 25));
        jtf_professor1.setMinimumSize(new java.awt.Dimension(70, 25));
        jtf_professor1.setPreferredSize(new java.awt.Dimension(70, 25));
        jtf_professor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_professor1ActionPerformed(evt);
            }
        });

        jtf_data.setBackground(new java.awt.Color(168, 214, 209));
        jtf_data.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtf_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_data.setText("Data:");
        jtf_data.setMaximumSize(new java.awt.Dimension(70, 25));
        jtf_data.setMinimumSize(new java.awt.Dimension(70, 25));
        jtf_data.setPreferredSize(new java.awt.Dimension(70, 25));
        jtf_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_dataActionPerformed(evt);
            }
        });

        btn_agendar.setText("Agendar");
        btn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPScheduleLayout = new javax.swing.GroupLayout(jPSchedule);
        jPSchedule.setLayout(jPScheduleLayout);
        jPScheduleLayout.setHorizontalGroup(
            jPScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPScheduleLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPScheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPScheduleLayout.createSequentialGroup()
                                .addComponent(jtf_professor1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cb_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPScheduleLayout.createSequentialGroup()
                                .addComponent(jtf_data, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cb_data, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPScheduleLayout.createSequentialGroup()
                                .addComponent(jtf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cb_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPScheduleLayout.setVerticalGroup(
            jPScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPScheduleLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_professor1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btn_agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        getContentPane().add(jPSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        jPConfigs.setBackground(new java.awt.Color(3, 152, 158));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Configurações");

        javax.swing.GroupLayout jPConfigsLayout = new javax.swing.GroupLayout(jPConfigs);
        jPConfigs.setLayout(jPConfigsLayout);
        jPConfigsLayout.setHorizontalGroup(
            jPConfigsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConfigsLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPConfigsLayout.setVerticalGroup(
            jPConfigsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConfigsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        getContentPane().add(jPConfigs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        jBHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHomeActionPerformed(evt);
            }
        });
        getContentPane().add(jBHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 50, 40));

        jBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jBSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 50, 40));

        jBSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBScheduleActionPerformed(evt);
            }
        });
        getContentPane().add(jBSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 50, 40));

        jBConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfigurationActionPerformed(evt);
            }
        });
        getContentPane().add(jBConfiguration, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 49, 40));

        panel_body.setBackground(new java.awt.Color(255, 255, 255));
        panel_body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 82, 240, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSearchActionPerformed
        // TODO add your handling code here:
        fecharTodasTelas();
        jPTeachers.setVisible(true);
    }//GEN-LAST:event_jBSearchActionPerformed

    private void jBHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHomeActionPerformed
        // TODO add your handling code here:
        fecharTodasTelas();
        jPHome.setVisible(true);
    }//GEN-LAST:event_jBHomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("caminho da imagem")));
        
        jLAvalibleTeachers.setModel(new javax.swing.AbstractListModel<String>() {
            public String[] strings = {"João", "Ricardo", "Maria", "Letícia", "Roberto", "Roque", "Ana Clara", "Diego"};
            @Override
            public int getSize() { return strings.length; }
            @Override
            public String getElementAt(int i) { return strings[i]; }
        });
        
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dataActionPerformed

    private void jtf_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_horarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_horarioActionPerformed

    private void jtf_professor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_professor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_professor1ActionPerformed

    private void jtf_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dataActionPerformed

    private void btn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarActionPerformed
        JOptionPane.showMessageDialog(null, " AULA  AGENDADA COM SUCESSO!!! \n\n "
            +"\nProfessor: " +cb_professor.getSelectedItem()
            +"\nAgendado dia: " + cb_data.getSelectedItem()
            +" Ã¡s " +cb_horario.getSelectedItem()
        );
    }//GEN-LAST:event_btn_agendarActionPerformed

    private void jBScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBScheduleActionPerformed
        // TODO add your handling code here:
        fecharTodasTelas();
        jPSchedule.setVisible(true);
    }//GEN-LAST:event_jBScheduleActionPerformed

    private void jBConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfigurationActionPerformed
        // TODO add your handling code here:
        fecharTodasTelas();
        jPConfigs.setVisible(true);
    }//GEN-LAST:event_jBConfigurationActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        fecharTodasTelas();
        jPLoginCadastrar.setVisible(true);
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed
        // TODO add your handling code here:
        fecharTodasTelas();
        jPLoginEntrar.setVisible(true);
    }//GEN-LAST:event_jBEntrarActionPerformed

    private void jBRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegisterActionPerformed
        // TODO add your handling code here:
        BDConnection bd = new BDConnection();
        bd.conectarBanco();
        bd.bdCadastrarAluno(jTFNome.getText(), jTFEmail.getText(), jTFSenha.getText(), jTFTelefone.getText(), jTFCPF.getText());
    }//GEN-LAST:event_jBRegisterActionPerformed

    private void jLVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVoltarMouseClicked
        // TODO add your handling code here:
        voltarJanelaLogin();
    }//GEN-LAST:event_jLVoltarMouseClicked

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        // TODO add your handling code here:
        BDConnection bd = new BDConnection();
        bd.conectarBanco();
        String senha = bd.bdConsultarLoginAluno(jTFLoginEmail.getText());

        System.out.println("senha: " + senha);

        if(senha == null){
            jLInformacoes.setText("Usuário não cadastrado!!!");
        }else{
            if(jTFLoginSenha.getText().equals(senha)){
                jLInformacoes.setText("Senha correta, aguarde...");
                fecharTodasTelas();
                jPHome.setVisible(true);
            }else{
                jLInformacoes.setText("Senha incorreta");
            }
        }

    }//GEN-LAST:event_jBLoginActionPerformed

    private void jLVoltar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVoltar2MouseClicked
        // TODO add your handling code here:
        voltarJanelaLogin();
    }//GEN-LAST:event_jLVoltar2MouseClicked
    
//    /**;
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agendar;
    private javax.swing.JComboBox<String> cb_data;
    private javax.swing.JComboBox<String> cb_horario;
    private javax.swing.JComboBox<String> cb_professor;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBConfiguration;
    private javax.swing.JButton jBEntrar;
    private javax.swing.JButton jBHome;
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jBRegister;
    private javax.swing.JButton jBSchedule;
    private javax.swing.JButton jBSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList<String> jLAvalibleTeachers;
    private javax.swing.JLabel jLInformacoes;
    private javax.swing.JLabel jLVoltar;
    private javax.swing.JLabel jLVoltar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPConfigs;
    private javax.swing.JPanel jPHome;
    private javax.swing.JPanel jPLogin;
    private javax.swing.JPanel jPLoginCadastrar;
    private javax.swing.JPanel jPLoginEntrar;
    private javax.swing.JPanel jPSchedule;
    private javax.swing.JPanel jPTeachers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCPF;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFLoginEmail;
    private javax.swing.JTextField jTFLoginSenha;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFSenha;
    private javax.swing.JTextField jTFTelefone;
    private javax.swing.JTextField jtf_data;
    private javax.swing.JTextField jtf_horario;
    private javax.swing.JTextField jtf_professor1;
    private javax.swing.JPanel panel_body;
    private javax.swing.JPanel panel_ini;
    // End of variables declaration//GEN-END:variables
}
